package br.com.btavares.avcd.model;
// Generated 07/10/2017 12:01:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name="images"
    ,catalog="acdatabase"
)
@XmlRootElement
public class Images  implements java.io.Serializable {


     private Integer imageId;
     private Products products;
     private String imageType;

    public Images() {
    }

    public Images(Products products, String imageType) {
       this.products = products;
       this.imageType = imageType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="image_id", unique=true, nullable=false)
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="image_type", length=20)
    public String getImageType() {
        return this.imageType;
    }
    
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }




}


