package br.com.btavares.avcd.model;
// Generated 07/10/2017 12:01:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="acdatabase"
)
@XmlRootElement
public class Products  implements java.io.Serializable {


     private Integer productId;
     private Products products;
     private String productName;
     private String description;
     private Set productses = new HashSet(0);
     private Set imageses = new HashSet(0);

    public Products() {
    }

    public Products(Products products, String productName, String description, Set productses, Set imageses) {
       this.products = products;
       this.productName = productName;
       this.description = description;
       this.productses = productses;
       this.imageses = imageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="product_name", length=50)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="description", length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products", targetEntity = br.com.btavares.avcd.model.Products.class)
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products", targetEntity = br.com.btavares.avcd.model.Images.class)
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }




}


